use super::super::component::*;
use crate::components::card::{Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle};
use dioxus::prelude::*;

/// Which of the two series the chart currently draws -- shadcn's own
/// `activeChart` state (`chart-line-interactive.tsx`'s
/// `React.useState<keyof typeof chartConfig>("desktop")`).
#[derive(Debug, Clone, Copy, PartialEq)]
enum Series {
    Desktop,
    Mobile,
}

impl Series {
    const ALL: [Series; 2] = [Series::Desktop, Series::Mobile];

    const fn key(self) -> &'static str {
        match self {
            Series::Desktop => "desktop",
            Series::Mobile => "mobile",
        }
    }

    const fn label(self) -> &'static str {
        match self {
            Series::Desktop => "Desktop",
            Series::Mobile => "Mobile",
        }
    }

    /// This series' position in [`ChartDatum::values`] (and in
    /// [`Self::ALL`]) -- `generate_data` always writes `[desktop, mobile]`
    /// in that order.
    const fn index(self) -> usize {
        match self {
            Series::Desktop => 0,
            Series::Mobile => 1,
        }
    }
}

/// Port of shadcn's `chart-line-interactive.tsx`
/// (`$S/refs/ui/apps/v4/registry/new-york-v4/charts/chart-line-interactive.tsx`,
/// clone commit `a87a63b`): a two-button header toggles which of two
/// series (desktop/mobile) the chart actually draws, each button showing
/// that series' running total. shadcn renders the toggle as two bare
/// `<button data-active>` elements in a plain flex row spanning the whole
/// card header width; this port instead places them in this theme's
/// existing `CardAction` slot (the same header-action pattern this
/// package's sibling `chart::variants::main` -- the interactive AREA chart
/// -- already uses for its own range `Select`), which keeps the layout
/// consistent with this design system's own header convention rather than
/// hand-rolling shadcn's bespoke `flex-col items-stretch sm:flex-row`
/// split. The buttons themselves are still real `button type="button"`
/// elements (`line_chart/style.css`'s `.dx-line-chart-toggle`), not a
/// styled `div` -- `data-active` (this crate's own established
/// true/false-string convention: `pagination`/`input_otp`/`sidebar`'s own
/// `component.rs` files) drives the pressed look, paired with a real
/// `aria-pressed` (shadcn's own source sets neither -- `data-active` there
/// is Tailwind-selector styling only -- but this crate pairs every
/// styling-only `data-*` state with real ARIA wherever one applies, the
/// same way `pagination`'s own `data-active` link is paired with
/// `aria-current="page"`).
///
/// 91 days of desktop/mobile data (April 1 - June 30), generated by a pure
/// function of the row index -- never shadcn's own literal 91-row array --
/// the same choice, for the same reason, this package's sibling
/// `chart::variants::main` (`preview/src/components/chart/variants/main/
/// mod.rs`) already made for its own 90-day interactive area-chart port:
/// a deterministic function of index keeps the server-prerendered and
/// post-hydration markup identical without transcribing 91 hand-copied
/// rows (dev-docs/recommended-implementations.md's hydration-parity rule).
/// The two buttons' totals are summed from this generated data at render
/// time, so they are internally consistent with the drawn chart even
/// though the exact numbers differ from shadcn's own hard-coded totals.
fn generate_data() -> Vec<ChartDatum> {
    const MONTHS: [(&str, u32); 3] = [("Apr", 30), ("May", 31), ("Jun", 30)];
    let mut data = Vec::with_capacity(91);
    let mut i: f64 = 0.0;
    for (name, days) in MONTHS {
        for day in 1..=days {
            let desktop = (230.0 + 160.0 * (i * 0.13).sin() + i * 0.7).max(15.0).round();
            let mobile = (210.0 + 150.0 * (i * 0.16 + 0.8).sin() + i * 0.5).max(15.0).round();
            data.push(ChartDatum {
                label: format!("{name} {day}"),
                values: vec![Some(desktop), Some(mobile)],
                ..Default::default()
            });
            i += 1.0;
        }
    }
    data
}

/// Thousands-grouped integer formatting (shadcn's own
/// `total[key].toLocaleString()`) -- e.g. `12345.0` -> `"12,345"`.
fn format_total(value: f64) -> String {
    let n = value.round() as i64;
    let digits = n.unsigned_abs().to_string();
    let mut grouped = String::new();
    for (i, ch) in digits.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            grouped.push(',');
        }
        grouped.push(ch);
    }
    let grouped: String = grouped.chars().rev().collect();
    if n < 0 {
        format!("-{grouped}")
    } else {
        grouped
    }
}

#[component]
pub fn Demo() -> Element {
    let mut active = use_signal(|| Series::Desktop);
    let data = generate_data();
    let totals: [f64; 2] = Series::ALL.map(|series| {
        data.iter()
            .filter_map(|d| d.values.get(series.index()).copied().flatten())
            .sum()
    });

    // Only the active series is configured/drawn -- matches the source's
    // own single `<Line dataKey={activeChart}>` (its `chartConfig`
    // declares both, but only one `<Line>` element exists in the JSX at a
    // time, driven by the same `activeChart` state).
    let current = active();
    let config = ChartConfig::new().series(current.key(), current.label(), "var(--dx-chart-1)");
    let visible: Vec<ChartDatum> = data
        .iter()
        .map(|d| ChartDatum {
            label: d.label.clone(),
            values: vec![d.values[current.index()]],
            ..Default::default()
        })
        .collect();

    rsx! {
        Card {
            CardHeader {
                CardTitle { "Line Chart - Interactive" }
                CardDescription { "Showing total visitors for the last 3 months" }
                CardAction {
                    div { class: "dx-line-chart-toggle-row",
                        for series in Series::ALL {
                            button {
                                key: "{series.key()}",
                                class: "dx-line-chart-toggle",
                                r#type: "button",
                                "data-active": series == current,
                                "aria-pressed": series == current,
                                onclick: move |_| active.set(series),
                                span { class: "dx-line-chart-toggle-label", "{series.label()}" }
                                span { class: "dx-line-chart-toggle-value",
                                    "{format_total(totals[series.index()])}"
                                }
                            }
                        }
                    }
                }
            }
            CardContent {
                ChartContainer { config, data: visible, kind: ChartKind::Line,
                    Chart {
                        aria_label: "Visitors by day, {current.label()}",
                        x_label: "Date",
                        curve: Curve::Monotone,
                    }
                    ChartTooltip {}
                }
            }
        }
    }
}
