#!/usr/bin/env node
// Generates preview/assets/theme-presets.css from shadcn's own theme DATA.
//
//   node dev-docs/research/theme-2026-10-03/tools/gen_presets.mjs \
//       --src /path/to/shadcn-ui/ui/apps/v4/registry --sha <git sha> [--out preview/assets/theme-presets.css]
//
// Sources (shadcn-ui/ui, apps/v4/registry):
//   themes.ts              THEMES: 7 base colours (neutral, stone, zinc, mauve, olive, mist, taupe -- the
//                          BASE_COLORS filter in base-colors.ts) and 17 accent themes (everything else).
//                          A base carries the full variable set; an accent carries only primary(-foreground),
//                          secondary(-foreground), chart-1..5 and sidebar-primary(-foreground).
//   _legacy-base-colors.ts baseColorsV4: gray and slate -- the two base colours the earlier shadcn customizer
//                          offered that themes.ts dropped. Same shape, same OKLCH, ported unchanged.
// shadcn composes a theme as `{...baseColor.cssVars, ...accent.cssVars}` (apps/v4/registry/config.ts
// buildRegistryTheme, app/(app)/(create)/lib/merge-theme.ts). Two attribute axes on <html>
// ([data-theme-base], [data-theme-accent]) reproduce exactly that merge through the cascade (accent
// blocks come later in the file), so 9 + 17 blocks stand in for every one of the 9 x 18 combinations.
//
// Values are copied verbatim. Each variable is written once with the light/dark space toggle that
// dx-components-theme.css already uses (`var(--dark, <dark>) var(--light, <light>)`), so the existing
// light/dark switch keeps working with any preset. `radius` is not emitted per base: shadcn keeps it as a
// separate axis (RADII in config.ts), which is [data-theme-radius] below.
import fs from "node:fs";
import path from "node:path";

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => (a.startsWith("--") ? [...acc, [a.slice(2), all[i + 1]]] : acc), []),
);
const src = args.src;
const sha = args.sha ?? "unknown";
const out = args.out ?? "preview/assets/theme-presets.css";
if (!src) {
  console.error("usage: gen_presets.mjs --src <apps/v4/registry> --sha <sha> [--out file]");
  process.exit(2);
}

function load(file, strip) {
  const text = strip(fs.readFileSync(path.join(src, file), "utf8"));
  const m = { exports: {} };
  new Function("module", text)(m);
  return m.exports;
}

const THEMES = load("themes.ts", (t) =>
  t
    .replace(/^import .*$/gm, "")
    .replace(/^export type .*$/gm, "")
    .replace("export const THEMES: RegistryItem[] =", "module.exports =")
    .replace(/\]\s*as const satisfies RegistryItem\[\]/, "]"),
);

const legacy = load("_legacy-base-colors.ts", (t) => {
  const i = t.indexOf("export const baseColorsV4 =");
  const j = t.indexOf("} as const", i);
  return t.slice(i, j + 1).replace("export const baseColorsV4 =", "module.exports =");
});

// BASE_COLORS from base-colors.ts, read rather than restated.
const baseNames = [...fs.readFileSync(path.join(src, "base-colors.ts"), "utf8").matchAll(/"([a-z]+)"/g)].map((m) => m[1]);
const title = (s) => s[0].toUpperCase() + s.slice(1);
const bases = baseNames.map((n) => THEMES.find((t) => t.name === n));
["gray", "slate"].forEach((n, i) => {
  bases.splice(3 + i, 0, { name: n, title: title(n), cssVars: legacy[n] }); // neutral stone zinc gray slate mauve ...
});
const accents = THEMES.filter((t) => !baseNames.includes(t.name));

function block(selector, theme, note) {
  const { light, dark } = theme.cssVars;
  const keys = [...new Set([...Object.keys(light), ...Object.keys(dark)])].filter((k) => k !== "radius");
  const skipped = [];
  const lines = [];
  for (const k of keys) {
    const l = light[k];
    const d = dark[k];
    // A variable one mode defines and the other does not cannot be expressed with the space toggle (the
    // undefined mode would resolve to an empty value, not to the base's), so it is left out and reported.
    // shadcn@295a1f1 has exactly one: rose's dark block carries a stray `sidebar` with no light counterpart.
    if (l === undefined || d === undefined) {
      skipped.push(`${k} (${l === undefined ? "dark" : "light"} only)`);
      continue;
    }
    lines.push(`  --${k}: ${l === d ? l : `var(--dark, ${d}) var(--light, ${l})`};`);
  }
  if (skipped.length) console.error(`warning: ${theme.name}: skipped ${skipped.join(", ")}`);
  const comment = [note, skipped.length ? `skipped, defined in one mode only upstream: ${skipped.join(", ")}` : ""].filter(Boolean).join(" -- ");
  return `${comment ? `/* ${comment} */\n` : ""}${selector} {\n${lines.join("\n")}\n}\n`;
}

const RADII = ["0", "0.3", "0.5", "0.625", "0.75", "1"];

let css = `/* GENERATED by dev-docs/research/theme-2026-10-03/tools/gen_presets.mjs -- do not edit by hand.
 *
 * shadcn's theme customizer, as DATA. Source: shadcn-ui/ui@${sha}
 * (apps/v4/registry/themes.ts for ${baseNames.length} base colours and ${accents.length} accents; registry/_legacy-base-colors.ts
 * baseColorsV4 for gray and slate). OKLCH values are verbatim.
 *
 * How it applies. Each block sets shadcn's BARE variables (--background, --primary, ...) on <html>.
 * dx-components-theme.css reads those first (--dx-primary: var(--primary, <ramp>)), so every component
 * recolours with no component edit. No attribute set = no preset = the library's own look.
 *
 *   <html data-theme-base="zinc" data-theme-accent="blue" data-theme-radius="0.5">
 *
 * Two axes, composed by the cascade exactly like shadcn's { ...baseColor, ...accent } merge: a base sets the
 * whole palette, an accent overrides primary/secondary/chart/sidebar-primary, so accent blocks must stay
 * after base blocks. Each variable carries both modes with the same space toggle the theme file uses
 * (var(--dark, <dark>) var(--light, <light>)), so the light/dark switch works with any preset.
 *
 * Attributes live on <html> because the --dx-* role tokens are declared on :root and resolve the bare
 * variables there. Set by the pre-paint snippet in preview/index.html (cookies dx_theme_base/_accent/_radius).
 * The picker's swatches reuse these same blocks (preview/assets/main.css .dx-theme-swatch), so the colour
 * data exists in exactly one place.
 */

/* stylelint-disable lightness-notation, hue-degree-notation -- values are shadcn's, byte for byte (oklch(0.145 0 0), not 14.5% 0deg) */

/* Radius: shadcn's RADII, as the owner's list. --dx-radius reads --radius; the whole --dx-radius-* scale derives from it. */
`;
for (const r of RADII) {
  css += `[data-theme-radius="${r}"] {\n  --radius: ${r}rem;\n}\n\n`;
}

css += `/* Base colours. */

/* Two variables shadcn's v4 theme data does not carry, which the library's role tokens read (see the comments in
 * dx-components-theme.css), set under any base:
 *  - --border-strong: no shadcn counterpart. Derived from the base's own ink and page (about 26% ink: close to
 *    the ramp's #b0b0b0 / #3e3e3e), so hover borders keep the tint.
 *  - --destructive-foreground: v3 shipped it, v4 components hard-code \`text-white\` on destructive instead. Our
 *    \`--dx-destructive-foreground\` falls back to a ramp grey (#dcdcdc in dark) tuned for the ramp's own dark red;
 *    on shadcn's lighter dark destructive it is 4.37:1 on a button. Near-white matches what v4 paints. */
[data-theme-base] {
  --border-strong: color-mix(in oklab, var(--foreground) 26%, var(--background));
  --destructive-foreground: oklch(0.985 0 0);
}

`;
for (const t of bases) {
  css += block(`[data-theme-base="${t.name}"]`, t, t.title) + "\n";
}
css += `/* Accents: override the base's primary, secondary, charts and sidebar-primary. Must come after the bases. */\n\n`;
for (const t of accents) {
  css += block(`[data-theme-accent="${t.name}"]`, t, t.title) + "\n";
}

fs.writeFileSync(out, css.replace(/\n+$/, "\n"));
console.error(`wrote ${out}: ${bases.length} bases (${bases.map((b) => b.name).join(" ")}), ${accents.length} accents, ${css.split("\n").length} lines`);
