//! `add`, `remove` and `list`: dependency resolution, copying a component into the project, the
//! `mod.rs` bookkeeping and `cargo add`.
//!
//! Forked from dioxus-cli 0.7.9 `src/cli/component.rs` (`add_component`, `copy_component_files`,
//! `copy_global_assets`, `remove_component`, `ensure_components_module_exists`;
//! <https://github.com/DioxusLabs/dioxus>, `MIT OR Apache-2.0`). Differences from dx:
//!   * a bare-name `componentDependencies` entry resolves in the registry of the component that names
//!     it ([`dependency_source`]); dx resolves it in dx's own default registry, which is what sent
//!     `date_picker`'s `calendar` and `popover` to upstream and made the install die with "outside of
//!     the component registry";
//!   * each component copies its global assets from ITS OWN registry root, not the root of the
//!     registry named on the command line;
//!   * destinations are checked before anything is written or `cargo add`ed, so an "already exists"
//!     error leaves the project untouched;
//!   * dependencies install in a stable order, and `cargo add` runs only for components actually copied;
//!   * a global asset that already exists and differs (the theme, edited by its owner) is kept unless
//!     `--force`, instead of being overwritten by every later `add`;
//!   * `mod.rs` is created when missing even if its directory exists, and appended to safely.

use crate::lock::{read_tree, Lock};
use crate::manifest::{CargoDependency, ComponentDependency};
use crate::project::Project;
use crate::registry::{
    Registries, Registry, ResolvedComponent, Source, DEFAULT_REGISTRY_GIT_URL, REGISTRY_NAME,
};
use anyhow::{bail, Context, Result};
use std::{
    collections::HashMap,
    path::{Path, PathBuf},
};

/// What to do when a component's destination directory exists.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExistsBehavior {
    /// Fail (an explicitly requested component).
    Error,
    /// Skip silently (a dependency that is already installed).
    Return,
    /// Replace it (`--force`).
    Overwrite,
}

/// The header of a `mod.rs` this tool creates. Identical to dx's, so either installer recognises it.
pub const MOD_RS_HEADER: &str = "// AUTOGENERATED Components module\n";

fn same_url(a: &str, b: &str) -> bool {
    let norm = |s: &str| {
        s.trim_end_matches('/')
            .trim_end_matches(".git")
            .to_ascii_lowercase()
    };
    norm(a) == norm(b)
}

/// The registry a `componentDependencies` entry is resolved in, given the registry of the component
/// that names it.
///
///   * bare name: the SAME registry as the parent;
///   * `{ name, git, rev }`: that git repository, except
///       - when it is the parent's own git URL (and `rev`, if given, matches): the parent, so a
///         pinned or `file://` copy of a registry stays self-consistent;
///       - when the parent is this project's registry (root `component.json` named
///         [`REGISTRY_NAME`]) and the entry names [`DEFAULT_REGISTRY_GIT_URL`] without a `rev`: the
///         parent. Our own `component.json` files spell dependencies that way so that plain
///         `dx components add` resolves them; when we install from a checkout (`--path`), a
///         `file://` URL or a pinned `--rev`, those entries must follow the copy being installed,
///         not jump to whatever the network serves.
pub fn dependency_source(parent: &Registry, dependency: &ComponentDependency) -> Source {
    match dependency {
        ComponentDependency::Builtin(_) => parent.source.clone(),
        ComponentDependency::ThirdParty { git, rev, .. } => {
            let is_parent = match &parent.source {
                Source::Git {
                    url,
                    rev: parent_rev,
                } => same_url(url, git) && (rev.is_none() || rev == parent_rev),
                Source::Path(_) => false,
            };
            let is_self_reference = parent.name == REGISTRY_NAME
                && rev.is_none()
                && same_url(git, DEFAULT_REGISTRY_GIT_URL);
            if is_parent || is_self_reference {
                parent.source.clone()
            } else {
                Source::Git {
                    url: git.clone(),
                    rev: rev.clone(),
                }
            }
        }
    }
}

/// A component to install and how to treat an existing copy.
#[derive(Clone, Debug)]
pub struct Planned {
    pub component: ResolvedComponent,
    pub mode: ExistsBehavior,
}

/// The requested components plus every component they depend on, transitively, requested ones first
/// then dependencies in discovery order. A component reached twice is planned once; a requested
/// component keeps its own `mode` even if another one depends on it.
pub fn plan(
    registries: &mut Registries,
    registry: &Registry,
    requested: &[ResolvedComponent],
    mode: ExistsBehavior,
) -> Result<Vec<Planned>> {
    let mut planned: Vec<Planned> = Vec::new();
    let mut index: HashMap<PathBuf, usize> = HashMap::new();
    for component in requested {
        if !index.contains_key(&component.path) {
            index.insert(component.path.clone(), planned.len());
            planned.push(Planned {
                component: component.clone(),
                mode,
            });
        }
    }
    // Which registry each planned component came from, for resolving its dependencies.
    let mut origin: HashMap<PathBuf, Source> = planned
        .iter()
        .map(|p| (p.component.path.clone(), registry.source.clone()))
        .collect();
    let mut cursor = 0;
    while cursor < planned.len() {
        let parent = planned[cursor].component.clone();
        cursor += 1;
        let parent_source = origin[&parent.path].clone();
        let parent_registry = registries.get(&parent_source)?;
        for dependency in &parent.component_dependencies {
            let source = dependency_source(&parent_registry, dependency);
            let dep_registry = registries.get(&source)?;
            let found = dep_registry
                .find(dependency.name())
                .with_context(|| format!("required by component '{}'", parent.name))?;
            if !index.contains_key(&found.path) {
                index.insert(found.path.clone(), planned.len());
                origin.insert(found.path.clone(), source);
                planned.push(Planned {
                    component: found.clone(),
                    mode: ExistsBehavior::Return,
                });
            }
        }
    }
    Ok(planned)
}

/// `pub mod name;` added to `mod.rs` content, or `None` if a declaration of `name` is already there.
pub fn with_mod_line(content: &str, name: &str) -> Option<String> {
    if has_mod_line(content, name) {
        return None;
    }
    let mut out = content.to_owned();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&format!("pub mod {name};\n"));
    Some(out)
}

fn is_mod_line(line: &str, name: &str) -> bool {
    let line = line.trim();
    let line = line
        .strip_prefix("pub ")
        .map(str::trim_start)
        .unwrap_or(line);
    line == format!("mod {name};")
}

fn has_mod_line(content: &str, name: &str) -> bool {
    content.lines().any(|line| is_mod_line(line, name))
}

/// `content` without its declaration of module `name`, or `None` if it has none.
pub fn without_mod_line(content: &str, name: &str) -> Option<String> {
    if !has_mod_line(content, name) {
        return None;
    }
    Some(
        content
            .split_inclusive('\n')
            .filter(|line| !is_mod_line(line, name))
            .collect(),
    )
}

/// Create the components directory and its `mod.rs` if either is missing. Returns true if anything
/// was created.
pub fn ensure_components_module(components_dir: &Path) -> Result<bool> {
    let mod_rs = components_dir.join("mod.rs");
    if mod_rs.exists() {
        return Ok(false);
    }
    std::fs::create_dir_all(components_dir)?;
    std::fs::write(&mod_rs, MOD_RS_HEADER)
        .with_context(|| format!("Failed to write {}", mod_rs.display()))?;
    Ok(true)
}

/// Copy the files of a component. Returns false if it was skipped because it already exists.
fn copy_component_files(
    src: &Path,
    dest: &Path,
    exclude: &[String],
    behavior: ExistsBehavior,
) -> Result<bool> {
    if dest.exists() {
        match behavior {
            ExistsBehavior::Error => {
                bail!("Destination directory '{}' already exists", dest.display())
            }
            ExistsBehavior::Return => return Ok(false),
            ExistsBehavior::Overwrite => std::fs::remove_dir_all(dest)?,
        }
    }
    let excluded: Vec<PathBuf> = exclude.iter().map(|e| src.join(e)).collect();
    copy_dir(src, dest, &excluded)?;
    Ok(true)
}

fn copy_dir(src: &Path, dest: &Path, excluded: &[PathBuf]) -> Result<()> {
    std::fs::create_dir_all(dest)?;
    for entry in
        std::fs::read_dir(src).with_context(|| format!("Failed to read {}", src.display()))?
    {
        let path = entry?.path();
        if excluded.iter().any(|e| path.starts_with(e)) {
            continue;
        }
        let target = dest.join(path.file_name().context("path without a file name")?);
        if path.is_dir() {
            copy_dir(&path, &target, excluded)?;
        } else {
            std::fs::copy(&path, &target).with_context(|| {
                format!("Failed to copy {} to {}", path.display(), target.display())
            })?;
        }
    }
    Ok(())
}

/// What happened to one global asset.
#[derive(Debug, PartialEq, Eq)]
pub enum AssetOutcome {
    Copied(PathBuf),
    Unchanged(PathBuf),
    /// Exists, differs from the registry's copy, and was kept.
    Kept(PathBuf),
}

/// Copy the component's global assets into `assets_root`, from inside its own registry only.
///
/// With a `lock`, an existing asset that equals what this tool last wrote (you never edited it) is replaced by
/// the registry's newer copy even without `force`, and every asset that ends up equal to the registry's is
/// recorded as the new baseline.
pub fn copy_global_assets(
    assets_root: &Path,
    component: &ResolvedComponent,
    force: bool,
    mut lock: Option<&mut Lock>,
) -> Result<Vec<AssetOutcome>> {
    let mut outcomes = Vec::new();
    for path in &component.global_assets {
        let src = component.path.join(path);
        let absolute_source = std::fs::canonicalize(&src).with_context(|| {
            format!(
                "Failed to find global asset '{}' for component '{}'",
                src.display(),
                component.name
            )
        })?;
        if !absolute_source.starts_with(&component.registry_root) {
            bail!(
                "Cannot copy global asset '{}' for component '{}' because it is outside of the component registry '{}'",
                absolute_source.display(),
                component.name,
                component.registry_root.display()
            );
        }
        let dest = assets_root.join(
            absolute_source
                .file_name()
                .context("Global assets must be files")?,
        );
        let new_bytes = std::fs::read(&absolute_source)?;
        let file_name = dest
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        match std::fs::read(&dest) {
            Ok(old) if old == new_bytes => {
                if let Some(lock) = lock.as_deref_mut() {
                    lock.record_asset(&file_name, &new_bytes);
                }
                outcomes.push(AssetOutcome::Unchanged(dest));
                continue;
            }
            Ok(old)
                if !force
                    && !lock
                        .as_deref()
                        .is_some_and(|l| l.asset_untouched(&file_name, &old)) =>
            {
                outcomes.push(AssetOutcome::Kept(dest));
                continue;
            }
            _ => {}
        }
        std::fs::create_dir_all(assets_root)?;
        std::fs::write(&dest, &new_bytes).with_context(|| {
            format!(
                "Failed to copy global asset from {} to {}",
                src.display(),
                dest.display()
            )
        })?;
        if let Some(lock) = lock.as_deref_mut() {
            lock.record_asset(&file_name, &new_bytes);
        }
        outcomes.push(AssetOutcome::Copied(dest));
    }
    Ok(outcomes)
}

/// Options of `add`.
pub struct AddOptions<'a> {
    pub requested: &'a [String],
    pub all: bool,
    pub module_path: Option<&'a Path>,
    pub global_assets_path: Option<&'a Path>,
    pub force: bool,
    pub skip_cargo_add: bool,
}

/// Install components (and their dependencies) from `source` into `project`.
pub fn add(
    project: &Project,
    registries: &mut Registries,
    source: &Source,
    options: &AddOptions,
) -> Result<()> {
    let registry = registries.get(source)?;
    let requested: Vec<ResolvedComponent> = if options.all {
        registry.components.clone()
    } else {
        options
            .requested
            .iter()
            .map(|name| registry.find(name).cloned())
            .collect::<Result<_>>()?
    };
    let mode = if options.force {
        ExistsBehavior::Overwrite
    } else {
        ExistsBehavior::Error
    };
    let planned = plan(registries, &registry, &requested, mode)?;
    let components_root = project.components_root(options.module_path);
    let assets_root = project.assets_root(options.global_assets_path);

    // Nothing is written until every destination is known to be free.
    let taken: Vec<String> = planned
        .iter()
        .filter(|p| p.mode == ExistsBehavior::Error)
        .filter(|p| components_root.join(&p.component.name).exists())
        .map(|p| p.component.name.clone())
        .collect();
    if !taken.is_empty() {
        bail!(
            "Already installed in {}: {} (use --force to overwrite)",
            components_root.display(),
            taken.join(", ")
        );
    }
    let to_install: Vec<&Planned> = planned
        .iter()
        .filter(|p| {
            p.mode != ExistsBehavior::Return || !components_root.join(&p.component.name).exists()
        })
        .collect();

    let created_module = ensure_components_module(&components_root)?;
    let mut lock = Lock::load(&components_root)?;

    if !options.skip_cargo_add {
        let mut deps: Vec<&CargoDependency> = Vec::new();
        for planned in &to_install {
            for dep in &planned.component.cargo_dependencies {
                if !deps.iter().any(|d| d.add_args() == dep.add_args()) {
                    deps.push(dep);
                }
            }
        }
        add_rust_dependencies(&project.crate_root, &deps)?;
    }

    for Planned { component, mode } in &to_install {
        copy_component_files(
            &component.path,
            &components_root.join(&component.name),
            &component.exclude,
            *mode,
        )?;
        let origin = if component.registry_root == registry.root {
            String::new()
        } else {
            format!(" (from {})", component.registry_root.display())
        };
        lock.record_component(
            &component.name,
            &read_tree(&components_root.join(&component.name))?,
        );
        println!("Added component '{}'{origin}", component.name);
        if !components_root
            .join(&component.name)
            .join("mod.rs")
            .is_file()
        {
            eprintln!(
                "warning: the registry ships no {}/mod.rs, so `pub mod {};` will not compile until it has one \
                 (`mod component; pub use component::*;`)",
                component.name, component.name
            );
        }
        for outcome in copy_global_assets(&assets_root, component, options.force, Some(&mut lock))?
        {
            match outcome {
                AssetOutcome::Copied(path) => println!("  copied {}", path.display()),
                AssetOutcome::Unchanged(_) => {}
                AssetOutcome::Kept(path) => println!(
                    "  kept your modified {} (it differs from the registry's; --force replaces it)",
                    path.display()
                ),
            }
        }
        let mod_rs = components_root.join("mod.rs");
        let content = std::fs::read_to_string(&mod_rs)
            .with_context(|| format!("Failed to read {}", mod_rs.display()))?;
        if let Some(updated) = with_mod_line(&content, &component.name) {
            std::fs::write(&mod_rs, updated)
                .with_context(|| format!("Failed to write {}", mod_rs.display()))?;
        }
    }
    lock.save(&components_root)?;
    for p in planned.iter().filter(|p| {
        !to_install
            .iter()
            .any(|i| i.component.path == p.component.path)
    }) {
        println!(
            "Component '{}' is already installed; left unchanged",
            p.component.name
        );
    }

    if created_module {
        println!(
            "Created new components module at {}.",
            components_root.display()
        );
        println!("To finish setting up components, run `shadcn-dioxus init` (it declares `mod components;` and links the theme), or by hand:");
        println!("- add `mod components;` to your `main.rs`");
        println!(
            "- link `asset!(\"/assets/dx-components-theme.css\")` as a stylesheet in your app"
        );
    }
    Ok(())
}

pub(crate) fn add_rust_dependencies(
    crate_root: &Path,
    dependencies: &[&CargoDependency],
) -> Result<()> {
    for dep in dependencies {
        let status = dep
            .add_command()
            .current_dir(crate_root)
            .status()
            .with_context(|| {
                format!(
                    "Failed to run command to add dependency {} to Cargo.toml",
                    dep.name()
                )
            })?;
        if !status.success() {
            bail!("Failed to add dependency {} to Cargo.toml", dep.name());
        }
    }
    Ok(())
}

/// Remove installed components: their directory and their `mod.rs` line. Their dependencies stay.
pub fn remove(
    project: &Project,
    registries: &mut Registries,
    source: &Source,
    requested: &[String],
    all: bool,
    module_path: Option<&Path>,
) -> Result<()> {
    let components_root = project.components_root(module_path);
    let names: Vec<String> = if all {
        registries
            .get(source)?
            .components
            .iter()
            .map(|c| c.name.clone())
            .collect()
    } else {
        requested.to_vec()
    };
    let mod_rs = components_root.join("mod.rs");
    let mut lock = Lock::load(&components_root)?;
    for name in names {
        lock.components.remove(&name);
        let dir = components_root.join(&name);
        let existed = dir.exists();
        if existed {
            std::fs::remove_dir_all(&dir)
                .with_context(|| format!("Failed to remove {}", dir.display()))?;
        }
        let mut declared = false;
        if let Ok(content) = std::fs::read_to_string(&mod_rs) {
            if let Some(updated) = without_mod_line(&content, &name) {
                std::fs::write(&mod_rs, updated)
                    .with_context(|| format!("Failed to write {}", mod_rs.display()))?;
                declared = true;
            }
        }
        if existed || declared {
            println!("Removed component '{name}'");
        } else if !all {
            println!("Component '{name}' is not installed");
        }
    }
    lock.save(&components_root)?;
    Ok(())
}

/// Print `- name: description` for every component of the registry.
pub fn list(registries: &mut Registries, source: &Source) -> Result<()> {
    for component in &registries.get(source)?.components {
        println!("- {}: {}", component.name, component.description);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::test_support::write_component;
    use std::path::Path;

    /// A registry at `root` whose root manifest is named `name`.
    fn registry(root: &Path, name: &str, members: &[&str]) {
        let members = members
            .iter()
            .map(|m| format!("\"{m}\""))
            .collect::<Vec<_>>()
            .join(",");
        write_component(
            root,
            ".",
            &format!(r#"{{ "name": "{name}", "members": [{members}] }}"#),
        );
    }

    fn path_source(root: &Path) -> Source {
        Source::Path(root.to_path_buf())
    }

    fn names(planned: &[Planned]) -> Vec<&str> {
        planned.iter().map(|p| p.component.name.as_str()).collect()
    }

    fn plan_for(root: &Path, request: &[&str]) -> Result<Vec<String>> {
        let mut registries = Registries::new(root.join("no-cache"));
        let registry = registries.get(&path_source(root))?;
        let requested: Vec<_> = request
            .iter()
            .map(|n| registry.find(n).cloned())
            .collect::<Result<_>>()?;
        let planned = plan(
            &mut registries,
            &registry,
            &requested,
            ExistsBehavior::Error,
        )?;
        Ok(names(&planned).into_iter().map(str::to_owned).collect())
    }

    #[test]
    fn bare_name_dependencies_resolve_in_the_parents_registry() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        registry(
            root,
            "other-registry",
            &["c/picker", "c/calendar", "c/popover"],
        );
        write_component(
            root,
            "c/picker",
            r#"{ "name": "picker", "componentDependencies": ["calendar", "popover"] }"#,
        );
        write_component(
            root,
            "c/calendar",
            r#"{ "name": "calendar", "componentDependencies": ["popover"] }"#,
        );
        write_component(root, "c/popover", r#"{ "name": "popover" }"#);
        // Transitive, deduplicated (popover is reached twice), requested first.
        assert_eq!(
            plan_for(root, &["picker"]).unwrap(),
            ["picker", "calendar", "popover"]
        );
        // Requesting a dependency as well keeps one entry, in the requested position.
        assert_eq!(
            plan_for(root, &["popover", "picker"]).unwrap(),
            ["popover", "picker", "calendar"]
        );
    }

    #[test]
    fn a_missing_dependency_names_the_requirer_and_the_registry() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        registry(root, "r", &["a"]);
        write_component(
            root,
            "a",
            r#"{ "name": "a", "componentDependencies": ["ghost"] }"#,
        );
        let err = format!("{:#}", plan_for(root, &["a"]).unwrap_err());
        assert!(
            err.contains("required by component 'a'") && err.contains("'ghost' not found"),
            "{err}"
        );
    }

    #[test]
    fn our_registrys_object_form_dependencies_follow_the_installed_copy() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        registry(root, REGISTRY_NAME, &["picker", "cal"]);
        write_component(
            root,
            "picker",
            &format!(
                r#"{{ "name": "picker", "componentDependencies": [{{ "name": "cal", "git": "{DEFAULT_REGISTRY_GIT_URL}" }}] }}"#
            ),
        );
        write_component(root, "cal", r#"{ "name": "cal" }"#);
        // No network and no cache: this only passes if "cal" is taken from the local copy.
        assert_eq!(plan_for(root, &["picker"]).unwrap(), ["picker", "cal"]);
    }

    #[test]
    fn dependency_source_rules() {
        let parent = |source: Source, name: &str| Registry {
            source,
            root: PathBuf::from("/r"),
            name: name.into(),
            components: vec![],
        };
        let obj = |git: &str, rev: Option<&str>| ComponentDependency::ThirdParty {
            name: "x".into(),
            git: git.into(),
            rev: rev.map(Into::into),
        };
        let git = |url: &str, rev: Option<&str>| Source::Git {
            url: url.into(),
            rev: rev.map(Into::into),
        };

        // bare name: always the parent's registry, whatever it is.
        let third = parent(git("https://t/t", Some("v2")), "third-party");
        assert_eq!(
            dependency_source(&third, &ComponentDependency::Builtin("x".into())),
            third.source
        );
        // object naming the parent's own URL (spelling variants, and a matching or absent rev).
        assert_eq!(
            dependency_source(&third, &obj("https://T/t.git/", None)),
            third.source
        );
        assert_eq!(
            dependency_source(&third, &obj("https://t/t", Some("v2"))),
            third.source
        );
        // another repository, or another rev of this one: fetched from where it says.
        assert_eq!(
            dependency_source(&third, &obj("https://z/z", None)),
            git("https://z/z", None)
        );
        assert_eq!(
            dependency_source(&third, &obj("https://t/t", Some("v3"))),
            git("https://t/t", Some("v3"))
        );
        // a third-party registry naming OUR url is a genuine third-party dependency.
        assert_eq!(
            dependency_source(&third, &obj(DEFAULT_REGISTRY_GIT_URL, None)),
            git(DEFAULT_REGISTRY_GIT_URL, None)
        );
        // our own registry naming itself follows the installed copy, pinned or local.
        let ours_local = parent(Source::Path("/co".into()), REGISTRY_NAME);
        assert_eq!(
            dependency_source(&ours_local, &obj(DEFAULT_REGISTRY_GIT_URL, None)),
            ours_local.source
        );
        let ours_pinned = parent(git("file:///co", Some("abc")), REGISTRY_NAME);
        assert_eq!(
            dependency_source(&ours_pinned, &obj(DEFAULT_REGISTRY_GIT_URL, None)),
            ours_pinned.source
        );
        // ... but an explicit rev is honoured.
        assert_eq!(
            dependency_source(&ours_local, &obj(DEFAULT_REGISTRY_GIT_URL, Some("v9"))),
            git(DEFAULT_REGISTRY_GIT_URL, Some("v9"))
        );
    }

    #[test]
    fn mod_rs_editing() {
        assert_eq!(with_mod_line("", "a").as_deref(), Some("pub mod a;\n"));
        // appends safely to a file without a trailing newline, and never duplicates.
        assert_eq!(
            with_mod_line("pub mod a;", "b").as_deref(),
            Some("pub mod a;\npub mod b;\n")
        );
        assert_eq!(with_mod_line("pub mod a;\n", "a"), None);
        assert_eq!(with_mod_line("mod a;\n", "a"), None);
        // a longer name is not the same module.
        assert_eq!(
            with_mod_line("pub mod date_button;\n", "button").as_deref(),
            Some("pub mod date_button;\npub mod button;\n")
        );
        assert_eq!(
            without_mod_line("pub mod a;\npub mod b;\n", "a").as_deref(),
            Some("pub mod b;\n")
        );
        assert_eq!(without_mod_line("pub mod a;\n", "zz"), None);
    }

    fn options(requested: &[String]) -> AddOptions<'_> {
        AddOptions {
            requested,
            all: false,
            module_path: None,
            global_assets_path: None,
            force: false,
            skip_cargo_add: true,
        }
    }

    fn project(root: &Path) -> Project {
        std::fs::write(root.join("Cargo.toml"), "[package]\nname = \"app\"\n").unwrap();
        Project::discover(root).unwrap()
    }

    #[test]
    fn add_installs_dependencies_assets_and_refuses_before_writing() {
        let tmp = tempfile::tempdir().unwrap();
        let reg = tmp.path().join("reg");
        registry(&reg, "r", &["button", "picker"]);
        write_component(
            &reg,
            "button",
            r#"{ "name": "button", "exclude": ["component.json", "variants", "missing"], "globalAssets": ["../theme.css"] }"#,
        );
        std::fs::create_dir_all(reg.join("button/variants")).unwrap();
        std::fs::write(reg.join("button/variants/demo.rs"), "demo").unwrap();
        std::fs::write(reg.join("theme.css"), "theme v1").unwrap();
        write_component(
            &reg,
            "picker",
            r#"{ "name": "picker", "componentDependencies": ["button"], "globalAssets": ["../theme.css"] }"#,
        );

        let app = tmp.path().join("app");
        std::fs::create_dir_all(&app).unwrap();
        let project = project(&app);
        let mut registries = Registries::new(tmp.path().join("cache"));
        let picker = [String::from("picker")];
        add(
            &project,
            &mut registries,
            &path_source(&reg),
            &options(&picker),
        )
        .unwrap();

        let comps = app.join("src/components");
        assert_eq!(
            std::fs::read_to_string(comps.join("mod.rs")).unwrap(),
            "// AUTOGENERATED Components module\npub mod picker;\npub mod button;\n"
        );
        assert!(comps.join("button/component.rs").is_file());
        assert!(
            !comps.join("button/variants").exists(),
            "excluded directory was copied"
        );
        assert!(!comps.join("button/component.json").exists());
        assert_eq!(
            std::fs::read_to_string(app.join("assets/theme.css")).unwrap(),
            "theme v1"
        );

        // A second add of something already there fails BEFORE touching anything.
        let both = [String::from("button"), String::from("picker")];
        let before = std::fs::read_to_string(comps.join("mod.rs")).unwrap();
        let err = add(
            &project,
            &mut registries,
            &path_source(&reg),
            &options(&both),
        )
        .unwrap_err();
        assert!(err.to_string().contains("button, picker"), "{err}");
        assert_eq!(
            std::fs::read_to_string(comps.join("mod.rs")).unwrap(),
            before
        );

        // A user-edited theme survives another add; --force replaces it.
        std::fs::write(app.join("assets/theme.css"), "my theme").unwrap();
        std::fs::remove_dir_all(comps.join("button")).unwrap();
        let button = [String::from("button")];
        add(
            &project,
            &mut registries,
            &path_source(&reg),
            &options(&button),
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(app.join("assets/theme.css")).unwrap(),
            "my theme"
        );
        let forced = AddOptions {
            force: true,
            ..options(&button)
        };
        add(&project, &mut registries, &path_source(&reg), &forced).unwrap();
        assert_eq!(
            std::fs::read_to_string(app.join("assets/theme.css")).unwrap(),
            "theme v1"
        );
        assert_eq!(
            std::fs::read_to_string(comps.join("mod.rs"))
                .unwrap()
                .matches("pub mod button;")
                .count(),
            1
        );

        // remove
        remove(
            &project,
            &mut registries,
            &path_source(&reg),
            &button,
            false,
            None,
        )
        .unwrap();
        assert!(!comps.join("button").exists());
        assert!(!std::fs::read_to_string(comps.join("mod.rs"))
            .unwrap()
            .contains("button"));
    }

    #[test]
    fn global_assets_may_not_escape_their_own_registry() {
        let tmp = tempfile::tempdir().unwrap();
        let reg = tmp.path().join("reg");
        registry(&reg, "r", &["a"]);
        write_component(
            &reg,
            "a",
            r#"{ "name": "a", "globalAssets": ["../../outside.css"] }"#,
        );
        std::fs::write(tmp.path().join("outside.css"), "x").unwrap();
        let mut registries = Registries::new(tmp.path().join("cache"));
        let registry = registries.get(&path_source(&reg)).unwrap();
        let err = copy_global_assets(
            &tmp.path().join("assets"),
            registry.find("a").unwrap(),
            false,
            None,
        )
        .unwrap_err();
        assert!(
            err.to_string()
                .contains("outside of the component registry"),
            "{err}"
        );
    }
}
