name: Web

# Automatic triggers disabled until further notice (2026-08-30).
# To reactivate, delete the 'on: workflow_dispatch' line and uncomment:
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]
#     branches:
#       - main
#
on: workflow_dispatch
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: DioxusLabs/dioxus-ci/.github/workflows/web-build.yml@v0.1.0
    with:
      working-directory: preview
      ssg: true
      features: fullstack
      base-path: ${{ github.event.repository.name }}
      dx-cli-version: 0.7.9
